In [ ]:
!pip install streamlit

Collecting streamlit
  Downloading streamlit-1.36.0-py2.py3-none-any.whl (8.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 10.4 MB/s eta 0:00:00
Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.2.2)
Requirement already satisfied: blinker<2,>=1.0.0 in /usr/lib/python3/dist-packages (from streamlit) (1.4)
Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<3,>=1.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.25.2)
Requirement already satisfied: packaging<25,>=20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.0.3)
Requirement already satisfied: pillow<11,>=7.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (9.4.0)
Requirement already satisfied: protobuf<6,>=3.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.20.3)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (14.0.2)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.31.0)
Requirement already satisfied: rich<14,>=10.14.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (13.7.1)
Requirement already satisfied: tenacity<9,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.4.2)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.12.2)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading GitPython-3.1.43-py3-none-any.whl (207 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 6.6 MB/s eta 0:00:00
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 23.1 MB/s eta 0:00:00
Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (6.3.3)
Collecting watchdog<5,>=2.1.5 (from streamlit)
  Downloading watchdog-4.0.1-py3-none-manylinux2014_x86_64.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.0/83.0 kB 3.5 MB/s eta 0:00:00
Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (4.19.2)
Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.12.1)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading gitdb-4.0.11-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 2.6 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2024.6.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (2.16.1)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading smmap-5.0.1-py3-none-any.whl (24 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.5)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.18.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)
Installing collected packages: watchdog, smmap, pydeck, gitdb, gitpython, streamlit
Successfully installed gitdb-4.0.11 gitpython-3.1.43 pydeck-0.9.1 smmap-5.0.1 streamlit-1.36.0 watchdog-4.0.1

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
os.chdir('/content/drive/MyDrive/Python/bread')

In [6]:
from google.colab import files
files.view("test.py")

In [5]:
!streamlit run test.py & sleep 3 && npx localtunnel --port 8501

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.75.210.210:8501

npx: installed 22 in 3.777s
your url is: https://famous-cloths-hang.loca.lt
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2